### ISSUE TITLE
sorting stops with checkbox in row

### ISSUE THREAD

**Issue by it-ben** [FyiurAmron/sortablejs#37] opened 2021-02-04 12:14 UTC
If you add a checkbox to a row, sortable stops sorting from this column till end of page. All before is sorted correctly.

**Comment by FyiurAmron** [comment] 2022-08-24 13:11
@it-ben I can't reproduce this. (see images below) Please provide a clear repro case (wiki markup you used, exact dokuwiki version & runtime platform, exact browser version & platform), otherwise I won't be able to help. Debugging info & PRs are welcome, too.

![image](https://user-images.githubusercontent.com/11016998/186427038-37fe2a82-3a15-444b-b574-ef267abe08fe.png)
![image](https://user-images.githubusercontent.com/11016998/186427099-f1fd1f5d-c2c3-4a6a-9d74-16d789b819c6.png)

**Comment by FyiurAmron** [comment] 2022-09-05 11:44
@it-ben I'm closing because of missing repro information.

**Closed by FyiurAmron** 2022-09-05 11:44 UTC
