### ISSUE TITLE
Formatted numbers (e.g. "20,000") treated as strings, sorting incorrectly

### ISSUE THREAD

**Issue by luckyshot** [FyiurAmron/sortablejs#33] opened 2019-05-27 08:38 UTC
When sorting columns that have commas, the columns are treated as strings and don't get sorted correctly. Example of sorting High to Low:

- `500`
- `400`
- `3,000`
- `300`
- `100`

I've tried forcing the column to be numeric (`1=numeric`) but didn't help.

Not sure what the most performant way to fix this is, but a RegExp positive match of `[0-9,\.]` could then remove the commas internally so sorting works. Currency symbols (`$€£`...) could be added too.

**Comment by FyiurAmron** [comment] 2022-08-24 12:55
@luckyshot 

distinguishing digit group separator from decimal separator is impossible without having a locale information (some locales use 1,000.2 - other use 1.000,2). Currently, AFAIR, both `,` and `.` are treated like decimal separators, since this is the most common case (i.e. 95%-ish of the cases). Also, I wasn't able to reproduce what you provided; in my case, the sorting went like this:

![image](https://user-images.githubusercontent.com/11016998/186422920-3a76dc92-30e1-4bc1-b4b5-c8b7ee377f4d.png)
![image](https://user-images.githubusercontent.com/11016998/186422990-39d72990-3c37-478e-8dbb-01e142bf221b.png)

... and that's exactly as expected.

Please provide a repro case with other obviously needed additional information (i.e. your exact browser version & platform) and  (since IMHO this is an ehancement request) a proposed solution, otherwise I won't be able to help here.

**Comment by FyiurAmron** [comment] 2022-08-24 13:54
@luckyshot FWIW, you can use standard JS group separator `_` instead.

**Comment by FyiurAmron** [comment] 2022-09-05 11:44
@luckyshot I'm closing because of missing repro information.

**Closed by FyiurAmron** 2022-09-05 11:44 UTC
