### ISSUE TITLE
3phase original order doesn't work

### ISSUE THREAD

**Issue by it-ben** [FyiurAmron/sortablejs#38] opened 2021-02-04 13:21 UTC
A table with 3phase option works correctly normal and reverse, but back to original order does sorts wild. After this, it is not possible to sort correctly normal and reverse. You have to reload the page.

**Comment by FyiurAmron** [comment] 2022-08-24 13:32
@it-ben I can't reproduce this. (see images below) Please provide a clear repro case (wiki markup you used, exact dokuwiki version & runtime platform, exact browser version & platform), otherwise I won't be able to help. Debugging info & PRs are welcome, too.

![image](https://user-images.githubusercontent.com/11016998/186431602-7f131c5a-47a2-4e71-a259-844e873f7ec2.png)
![image](https://user-images.githubusercontent.com/11016998/186431449-b3e22315-e090-42ef-818b-8287ffe9109e.png)
![image](https://user-images.githubusercontent.com/11016998/186431529-337a8e03-6ad8-4640-811b-e4430c6c2503.png)
![image](https://user-images.githubusercontent.com/11016998/186431604-8d6de862-de54-4ee5-8b2e-dc124851437c.png)

**Comment by FyiurAmron** [comment] 2022-09-05 11:44
@it-ben I'm closing because of missing repro information.

**Closed by FyiurAmron** 2022-09-05 11:44 UTC
