### ISSUE TITLE
Sorttable doesn't allow sorting of large tables (sorting links do not show up)

### ISSUE THREAD

**Issue by zimmerru** [FyiurAmron/sortablejs#31] opened 2017-12-05 16:29 UTC
I have a table with about 850 rows and 6 columns, and when I put it inside the sorttable tags the links to sort the columns do not show up.  It works fine on smaller tables.

**Comment by FyiurAmron** [comment] 2022-08-24 13:05
I can't reproduce it (in my case, 1024 rows & 6 columns work perfectly), and, since by itself the code has no limitation in this regard, looks like browser issue. Without any more specific info (browser version & platform), I can't fix it due to CANTREPRO. Even if I had that info, it'd probably be unfixable due to inherent browser limitations.

@zimmerru please provide a repro case if you still see this error. Otherwise I'll close this.

**Comment by FyiurAmron** [comment] 2022-09-05 11:43
@zimmerru I'm closing because of missing repro information.

**Closed by FyiurAmron** 2022-09-05 11:43 UTC
