### ISSUE TITLE
Only works on one table per page

### ISSUE THREAD

**Issue by professorq29** [FyiurAmron/sortablejs#45] opened 2023-04-17 06:13 UTC
I have multiple tables on a page and it only sorts on the top table. Others show the sort arrows but do nothing when clicked. Firefox browser.

**Comment by FyiurAmron** [comment] 2023-04-20 15:14
@professorq29 sorry, but I can't reproduce this, using Firefox 112.0.1 (64-bit) on Win7x64 and newest DW & sortablejs.

please provide more data (exact versions of system, browser, DokuWiki etc.) as well as JS console debugging logs (and PHP logs if you find them appropriate) if possible. Firefox is used by about 2-3% of users, and I haven't used it in ages myself, so this would be extremely low priority for me myself, but if you can give me something more to work with we can probably pinpoint this and fix it if it's actually reproducible on my machine.

Currently though, it's LGTM.

![image](https://user-images.githubusercontent.com/11016998/233410339-49ca89bb-099b-4dcd-a260-83c7bbcf2e44.png)
![image](https://user-images.githubusercontent.com/11016998/233410385-51b26f63-f807-4290-8a0a-b501c478029b.png)

**Comment by FyiurAmron** [comment] 2023-04-27 18:54
@professorq29 sadly, I'll have to close this due to being unable to reproduce and no further data from you. If you can help me with reproduction & additional data, feel free to do so here.

**Closed by FyiurAmron** 2023-04-27 18:54 UTC
