### ISSUE TITLE
Unable to modify column 10 onwards

### ISSUE THREAD

**Issue by calingasankj** [FyiurAmron/sortablejs#42] opened 2022-10-23 18:29 UTC
I wanted to remove sorting on columns 10-13

exmaple:
<sortable  9=nosort 10=nosort 11=nosort>

but it only stops at column 9

**Comment by FyiurAmron** [comment] 2022-10-25 20:17
@calingasankj I can confirm, :eyes: at it.

**Comment by FyiurAmron** [comment] 2022-10-25 20:27
caused by a faulty regex in `makeSortableDiv`; was
`var patt1 = /\bcol_\d_[a-z]+/gi;`
while it should be
`var patt1 = /\bcol_\d+_[a-z]+/gi;`

I will fix it and release shortly.

My test case:

test case:
```
<sortable 9=nosort 10=nosort 11=nosort>
^Col1^Col2^Col3^Col4^Col5^Col6^Col7^Col8^Col9^Col10^Col11^Col12^
|1,1|one|25/12/2008|1,1|one|25/12/2008|1,1|one|25/12/2008|1,1|one|25/12/2008|
|2,1|two|10/12/2008|2,1|two|10/12/2008|2,1|two|10/12/2008|2,1|two|10/12/2008|
|3a|three|15/12/2009|3a|three|15/12/2009|3a|three|15/12/2009|3a|three|15/12/2009|
|3b|three|:::|3b|three|:::|3b|three|:::|3b|three|:::|
</sortable>
```

**Comment by calingasankj** [comment] 2022-10-25 20:34
Thank you!! 😁😁 you found and fixedthe bug pretty quickly that's awesome 💯👏

**Comment by FyiurAmron** [comment] 2022-10-25 20:39
@calingasankj I've released a new version `2022-10-25` with this fixed, I'd be very grateful if you could update the plugin in your DW installation and check if the behaviour is now OK on your end.

**Comment by FyiurAmron** [comment] 2022-10-29 13:06
@calingasankj _bump_ can you verify it's working OK for you and, if so, close the issue? Thanks in advance.

**Comment by calingasankj** [comment] 2022-10-29 13:13
Sorry! I haven't been able to work on it for a while but I did try it out recently after updating and it's working great! Thank you

**Closed** 2022-10-29 13:14 UTC
